# Generated by Django 3.2.8 on 2021-12-06 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_poll_pollanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='slug',
            field=models.SlugField(default='default', max_length=250),
        ),
    ]
