# Generated by Django 3.2.8 on 2021-12-06 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_poll_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollanswer',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='blog.poll'),
        ),
    ]
