# Generated by Django 3.2.8 on 2021-12-06 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_pollanswer_poll'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
                ('pollAnswer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='blog.pollanswer')),
            ],
        ),
    ]
