# Generated by Django 3.2.8 on 2021-12-06 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_useranswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='pollAnswer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userAnswers', to='blog.pollanswer'),
        ),
    ]
