USE [master]
GO

/****** Object:  Database [Lab2Database]    Script Date: 9/20/2021 9:12:05 PM ******/
CREATE DATABASE [Lab2Database]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Lab2Database', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Lab2Database.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Lab2Database_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Lab2Database_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Lab2Database].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Lab2Database] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Lab2Database] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Lab2Database] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Lab2Database] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Lab2Database] SET ARITHABORT OFF 
GO

ALTER DATABASE [Lab2Database] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Lab2Database] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Lab2Database] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Lab2Database] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Lab2Database] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Lab2Database] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Lab2Database] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Lab2Database] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Lab2Database] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Lab2Database] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Lab2Database] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Lab2Database] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Lab2Database] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Lab2Database] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Lab2Database] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Lab2Database] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Lab2Database] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Lab2Database] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Lab2Database] SET  MULTI_USER 
GO

ALTER DATABASE [Lab2Database] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Lab2Database] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Lab2Database] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Lab2Database] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Lab2Database] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Lab2Database] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Lab2Database] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Lab2Database] SET  READ_WRITE 
GO


